version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1
  go: circleci/go@1.10.0

jobs:
  security-scans:
    executor:
      name: go/default
      tag: "1.21"
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: group-infrastructure-as-code-alerts
      - security-scans:
          name: "Security Scans"
          context:
            - analysis-iac
